/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nortenko Dmytro (https://sketchfab.com/leondp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/three-candles-and-a-golden-candlestick-9d46daabbefe4b4eab74d9da349dd015
Title: Three candles and a golden candlestick
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CandleHolder(props) {
  const { nodes, materials } = useGLTF('/3d-model/candle-holder.glb')
  return (
    <group scale={0.009} rotation={[0.0, 0.7, 0.0]} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.fire}
        position={[10.955, 106.092, -5.187]}
        rotation={[-Math.PI / 2, 0, 1.261]}
        scale={[100, 100, 121.073]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_1.geometry}
        material={materials.candlestick}
        position={[0, 19.686, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_2.geometry}
        material={materials.candles}
        position={[1.329, 50.636, -0.736]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload('/3d-model/candle-holder.glb')
